microsoftgraph/msgraph-beta-sdk-dotnet

pipelines/validatePR.yml

Ideally pull this in before #10

Add PR validation

---

appveyor.yml
pipelines/validatePR.yml
src/Microsoft.Graph/Models/Extensions/DateTimeZoneExtensions.cs
tests/Microsoft.Graph.DotnetCore.Test/Microsoft.Graph.DotnetCore.Test.csproj
tests/Microsoft.Graph.DotnetCore.Test/Models/Extensions/DateTimeZoneExtensionsTests.cs
tests/Microsoft.Graph.DotnetCore.Test/Models/Generated/EntityTests.cs

* migrated unit test project to dotnet core 2.2
* added new extension methods on datetimetimezone

Feature/date time extensions (#33)

---

src/Microsoft.Graph/Microsoft.Graph.Beta.csproj

Bump version

---

tests/Microsoft.Graph.DotnetCore.Test/Microsoft.Graph.DotnetCore.Test.csproj

https://docs.microsoft.com/en-us/dotnet/core/deploying/runtime-patch-selection

Use the default behavior for build

---

pipelines/generateServiceLibrary.yml

Found issue where multiple git commands (besides add + commit) in an inline script was causing an error.
https://github.com/microsoft/azure-pipelines-agent/issues/2860

Pipeline for generating service library

---

src/Microsoft.Graph/Microsoft.Graph.Beta.csproj

forgot to do this for manual generation and PR

Set version to 0.29.0

---

pipelines/generateServiceLibrary.yml
pipelines/validatePR.yml

Fix validate to run tests

---

.editorconfig
src/Microsoft.Graph/Microsoft.Graph.Beta.csproj
src/Microsoft.Graph/Requests/Extensions/ConnectorsRequestExtensions.cs
src/Microsoft.Graph/Requests/Extensions/TeamRequestExtensions.cs
tests/Microsoft.Graph.DotnetCore.Test/Microsoft.Graph.DotnetCore.Test.csproj
tests/Microsoft.Graph.DotnetCore.Test/Requests/Functional/GraphTestBase.cs
tests/Microsoft.Graph.DotnetCore.Test/Requests/Functional/MiscTests.cs

- Add ExternalItemRequest partial that supports push.
- Update dev test base to use client credential flow.
- Add dev test using generated doc code sample.
- Update test project to use latest C#.
@skyyy07X For review
Related https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/issues/314

Support put external item

---

README.md

The Issues link URL was broken

Fixed Issues link URL

---

src/Microsoft.Graph/Microsoft.Graph.Beta.csproj

Bump version to 0.42.x

---

src/Microsoft.Graph/Microsoft.Graph.Beta.csproj

Bump version to 0.43

---

src/Microsoft.Graph/Microsoft.Graph.Beta.csproj

Bump version to 0.44

---

src/Microsoft.Graph/Microsoft.Graph.Beta.csproj
src/Microsoft.Graph/Models/Extensions/ChangeNotification.cs
src/Microsoft.Graph/Models/Extensions/ChangeNotificationCollection.cs
src/Microsoft.Graph/Models/Extensions/ChangeNotificationEncryptedContent.cs
src/Microsoft.Graph/Models/Extensions/Subscription.cs

This PR is part of https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/268.
It complements the work in https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/269 and should build once its merged in.

Rich notification support

---

src/Microsoft.Graph/Generated/ediscovery/requests/ISourceCollectionCustodianSourcesCollectionReferencesRequest.cs
src/Microsoft.Graph/Generated/ediscovery/requests/ISourceCollectionNoncustodialSourcesCollectionReferencesRequest.cs
src/Microsoft.Graph/Generated/ediscovery/requests/ITagChildTagsCollectionReferencesRequest.cs
src/Microsoft.Graph/Generated/ediscovery/requests/SourceCollectionCustodianSourcesCollectionReferencesRequest.cs
src/Microsoft.Graph/Generated/ediscovery/requests/SourceCollectionNoncustodialSourcesCollectionReferencesRequest.cs
src/Microsoft.Graph/Generated/ediscovery/requests/TagChildTagsCollectionReferencesRequest.cs
src/Microsoft.Graph/Generated/requests/AccessPackageAccessPackagesIncompatibleWithCollectionReferencesRequest.cs
src/Microsoft.Graph/Generated/requests/AccessPackageIncompatibleAccessPackagesCollectionReferencesRequest.cs
src/Microsoft.Graph/Generated/requests/AccessPackageResourceEnvironmentAccessPackageResourcesCollectionReferencesRequest.cs
src/Microsoft.Graph/Generated/requests/ContentTypeBaseTypesCollectionReferencesRequest.cs
src/Microsoft.Graph/Generated/requests/ContentTypeColumnPositionsCollectionReferencesRequest.cs
src/Microsoft.Graph/Generated/requests/IAccessPackageAccessPackagesIncompatibleWithCollectionReferencesRequest.cs
src/Microsoft.Graph/Generated/requests/IAccessPackageIncompatibleAccessPackagesCollectionReferencesRequest.cs
src/Microsoft.Graph/Generated/requests/IAccessPackageResourceEnvironmentAccessPackageResourcesCollectionReferencesRequest.cs
src/Microsoft.Graph/Generated/requests/IContentTypeBaseTypesCollectionReferencesRequest.cs
src/Microsoft.Graph/Generated/requests/IContentTypeColumnPositionsCollectionReferencesRequest.cs
src/Microsoft.Graph/Generated/requests/ISiteExternalColumnsCollectionReferencesRequest.cs
src/Microsoft.Graph/Generated/requests/SiteExternalColumnsCollectionReferencesRequest.cs

Related to https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/596 and closes https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/issues/336
Updates validated as follows
"File Changed" => "possible navigation from serviceClass" - "referencePropertyName"
1. SourceCollectionCustodianSourcesCollectionReferencesRequest => **compliance/ediscovery/cases/{id}/noncustodialDataSources/{id}/dataSource** - custodianSources
2. SourceCollectionNoncustodialSourcesCollectionReferencesRequest => **compliance/ediscovery/cases/{id}/noncustodialDataSources/{id}** - noncustodialSources
3. TagChildTagsCollectionReferencesRequest => **compliance/ediscovery/cases/{id}/tags/{id}** -  childTags
4. AccessPackageAccessPackagesIncompatibleWithCollectionReferencesRequest => …

Fix for missing AddAsync methods for collection references (beta)

---

src/Microsoft.Graph/Requests/Extensions/UploadSessionRequest.cs
src/Microsoft.Graph/Requests/Helpers/ChunkedUploadProvider.cs
tests/Microsoft.Graph.DotnetCore.Test/Requests/Functional/UserActivitiesTests.cs

same fix as in https://github.com/microsoftgraph/msgraph-sdk-dotnet/pull/1194

disambiguate Task

---

.github/workflows/validatePullRequest.yml
Nuget.Config
README.md
src/Microsoft.Graph/GraphServiceClient.cs
src/Microsoft.Graph/Microsoft.Graph.Beta.csproj

This PR creates updates for the preview release
Changes include: 
- Introduced `GraphServiceClient` to tie to graph core
- Adds link to upgrade guide to cover changes from V4
- Update CI to use public sources.

Kiota preview updates

---

pipelines/validatePR.yml

Remove tests/* from excluded list for PR validation

---

pipelines/ci-build.yml
src/Microsoft.Graph/Microsoft.Graph.Beta.csproj

Related to https://github.com/microsoft/kiota/issues/2757

Fixes package icon/Readme and credscan version

---

tests/Microsoft.Graph.DotnetCore.Test/Requests/Functional/ExcelTests.cs
tests/Microsoft.Graph.DotnetCore.Test/Requests/Functional/ExtensionTests.cs
tests/Microsoft.Graph.DotnetCore.Test/Requests/Functional/GroupTests.cs
tests/Microsoft.Graph.DotnetCore.Test/Requests/Functional/MailTests.cs
tests/Microsoft.Graph.DotnetCore.Test/Requests/Functional/MiscTests.cs
tests/Microsoft.Graph.DotnetCore.Test/Requests/Functional/OneDriveTests.cs
tests/Microsoft.Graph.DotnetCore.Test/Requests/Functional/OneNoteTests.cs
tests/Microsoft.Graph.DotnetCore.Test/Requests/Functional/PlannerTests.cs
tests/Microsoft.Graph.DotnetCore.Test/Requests/Functional/ReportTests.cs
tests/Microsoft.Graph.DotnetCore.Test/Requests/Functional/SchemaExtensionTests.cs
tests/Microsoft.Graph.DotnetCore.Test/Requests/Functional/SharePointTests.cs
tests/Microsoft.Graph.DotnetCore.Test/Requests/Functional/UserActivitiesTests.cs
tests/Microsoft.Graph.DotnetCore.Test/Requests/Functional/UserTests.cs

Fixes warning after test package update via https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/pull/690

Fixes warnings in test projects

---

src/Microsoft.Graph/Microsoft.Graph.Beta.csproj

Adds trimming support

---

.github/ISSUE_TEMPLATE/01-sdk-bug.yml
.github/ISSUE_TEMPLATE/02-sdk-feature-request.yml
.github/ISSUE_TEMPLATE/03-blank-issue.md
.github/ISSUE_TEMPLATE/config.yml

Relates to https://github.com/microsoft/kiota/issues/4432

Add issue templating using issue forms

---

.github/ISSUE_TEMPLATE/config.yml

Related to https://github.com/microsoft/kiota-http-dotnet/issues/262

Chore: Add issue form templates

---

release-please-config.json

ci: fixes release please configuration

---

guardian/SDL/.gdnbaselines
guardian/SDL/.gdnsuppress

chore: update baselines due to false positives int dom export

---

guardian/SDL/.gdnbaselines
guardian/SDL/.gdnsuppress

chore: updates baselines with artifacts from latest run.

---

pipelines/ci-build.yml

Fixes https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/issues/976
Switches agent to avoid memorry pressure warnings and timeouts as seen in previoous runs.

chore: switch to PS agent

---

src/Microsoft.Graph/Extensions/DriveItemRequestBuilderExtensions.cs

reflection of https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2909

fix: drive item version pointed to list item versions
