microsoftgraph/msgraph-beta-sdk-dotnet

- src/Microsoft.Graph/Microsoft.Graph.Beta.csproj
- src/Microsoft.Graph/Models/Extensions/DateTimeZoneExtensions.cs
- tests/Microsoft.Graph.DotnetCore.Test/Models/Extensions/DateTimeZoneExtensionsTests.cs
This PR implements the Core enhancement as requested here [https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/366](https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/366)
It has two extension methods; 
-  **ToDateTime**
- **ToDateTimeOffset**
And two static methods;
- **FromDateTime**
- **FromDateTimeOffset**
Test methods were also added under **Microsoft.Graph.DotnetCore.Test > Models > Extensions**
Please note to accommodate some of the .Net built-in date functions and properties I updated the framework from .NETStandard 1.1 to .NETStandard 1.3
> DateTimeTimeZones extension methods implementation

- pipelines/validatePR.yml
Update validatePR.yml with:
* descriptive build name so it is easy to discern what pipeline a specific build is from.
* don't send fail notifications for manual builds.
> Descriptive build name and no notify manual build

- src/Microsoft.Graph/Microsoft.Graph.Beta.csproj
- src/Microsoft.Graph/Models/Extensions/UploadSession.cs
This PR updates UploadSession to implement IUploadSession to provide request builder compatibility with the LargeFileUploadTask work on this [PR](https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/65).
This should be merged in after the PR has been completed and deployed.
> Update UploadSession to implement new IUploadSession interface

- src/Microsoft.Graph/Microsoft.Graph.Beta.csproj
Customers should not use the preview any longer. We will delist the previews.
> Update M.G.C minimum package reference version

- scripts/runTypewriter.ps1
This change will allow us to run typewriter locally within the repo and from Azure Pipelines with the same script. 
Run the following from the repo root.
`.\scripts\runTypewriter.ps1 https://raw.githubusercontent.com/microsoftgraph/msgraph-metadata/master/clean_beta_metadata/cleanMetadataWithDescriptionsbeta.xml`
It should generate new code files and clean up the temporary files.
Will apply this to all repos that use generation.
> Run typewriter from within a repo

- .github/workflows/pull-request.yml
This will automatically open a PR when we have a branch spec that matches `"beta/pipelinebuild/*"`. We can remove the need to use GitHub/hub with PAT to create a PR.
This action is https://github.com/repo-sync/pull-request/tree/v2.0.0
> Add PR action

- scripts/bumpVersion.ps1
Reading the xml with correct encoding fixes the issue where script generates unwanted character in front of copyright.
Fixes #111
> Fix powershell script to not introduce unwanted character in front of copyright

- tests/Microsoft.Graph.DotnetCore.Test/Models/ModelSerializationTests.cs
This test is brittle as it depends on serialization order. A reorder in
the CSDL will break this test. That is what is precipitating this change.
This update is required for generation to successfully complete.
related: https://github.com/microsoftgraph/msgraph-sdk-dotnet/commit/8bd80488c725ed27bf1b45c4d313fc39c278d426
> Fix SerializeAndDeserializeKnownEnumValue test

- pipelines/generateServiceLibrary.yml
- scripts/generateTypeSummary.ps1
- src/Microsoft.Graph/Microsoft.Graph.Beta.csproj
- Adds generateTypeSummary script from msgraph-sdk-dotnet repo
- Adds pipeline steps to generate type summary
- Adds the initial `typeSummary.txt` file to represent current type list
- Fixes [skip ci] behavior for Github Action to skip generating PRs for manual runs
Perf: adds 3.5 minutes to Beta generation process, we can consider making this a separate stage if it is desired to be skipped in manual runs.
> Add type summary to Beta generation process

- README.md
Otherwise a little bit confusing.
Typo is just to be correct.
> Fixed typo and version number

- README.md
Fix the NuGet package link in the README to point to the Beta package. Fixes #181.
> Fix NuGet package link in README

- src/Microsoft.Graph/Microsoft.Graph.Beta.csproj
This PR is part of https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/219
This comes in as a new requirement as 4.6.1 is coming to EOL soon.
This PR updates the release notes in the csproj to capture recent updates to the branch
> Update minimum netframework to v4.6.2 in feature/2.0

- src/Microsoft.Graph/Microsoft.Graph.Beta.csproj
Fixes #133
Tested with a clone of the release pipeline, generated NuGet package passes the health checks.
Refer to [this documentation](https://github.com/clairernovotny/DeterministicBuilds#deterministic-builds) for deterministic builds.
PS. This is a POC work for FHL to go through the same process for `Microsoft.Graph`, `Microsoft.Graph.Auth` and `Microsoft.Graph.Core`.
> Add source link to enable debugging of our NuGet package

- scripts/GetNugetPackageVersion.ps1
Adding `symbols.nupkg` broke the regular expression that was extracting version information. This PR fixes that by assuming that there is a `*.symbols.nupkg` alongside `*.nupkg` file in the artifacts folder.
> fix version inference from .nupkg file

- pipelines/ci-build.yml
- src/Microsoft.Graph/Microsoft.Graph.Beta.csproj
Fixes #250
YAML is auto generated from the original build definition from the old project (0365 Sandbox). My main focus with this PR is to allow publishing of the symbols. We can consider moving the runner into Linux and refactoring the YAML, but I leave that to a further iteration.
The step that is modified is the powershell step that calls `dotnet pack`. Default `dotnet pack` task from Azure DevOps doesn't allow building snupkg files, so I had to introduce a manual `dotnet` call.
Release 0.40.3-preview contains the same code as 0.40.0-preview, except that it allows debugging with SourceLink and symbols. The couple of other patch upgrades, which are included in the commit history, were attempts to get the right symbol package work with the Azure DevOps release pipelines. They were signed …
> Migrate release build definition and build snupkg files as part of the pipeline

- README.md
- pipelines/ci-build.yml
- scripts/GetNugetPackageVersion.ps1
- src/Microsoft.Graph/Microsoft.Graph.Beta.csproj
This PR synchronizes the following PRs with the 2.0 branch to bring debug symbols support
#247 - Add source link to enable debugging of our NuGet package
#249 - fix version inference from .nupkg package
#251 - Migrate release build definition and build snupkg files as part of the pipeline
#259 - Fix prerelease instruction
Artifacts produced for this PR/branch can be found [here](https://o365exchange.visualstudio.com/O365%20Sandbox/_build/results?buildId=5003642&view=results).
> Debug Symbols support on feature/2.0

- src/Microsoft.Graph/Generated/requests/GraphServiceClient.cs
This PR closes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/916.
It enables the users of the SDK to define their own base address for the requestbuilders in the event they are using their own httpclient and varying clouds.
> Enable custom base address with httpclient constructor

- src/Microsoft.Graph/Generated/requests/GraphServiceClient.cs
This PR makes the properties of GraphServiceClient virtual to enable the use of mocking frameworks such as Moq to be able to override the implementations provided in the class after the dropping of the IGraphServiceClient interface.
Sdk users should now be able to initialize an mock of the GraphServiceClient for testing by doing something similar to the code below.
**Example**
```cs
// create mocks
var mockAuthProvider = new Mock<IAuthenticationProvider>();
var mockHttpProvider = new Mock<IHttpProvider>();
var mockGraphClient = new Mock<GraphServiceClient>(mockAuthProvider.Object, mockHttpProvider.Object);
ManagedDevice md = new ManagedDevice
{
Id = "1",
DeviceCategory = new DeviceCategory()
{
Description = "Sample Description"
}
};
// setup the calls
mockGraphClient.Setup(g => …
```
> Make properties of GraphServiceClient virtual (beta)

- pipelines/ci-build.yml
This PR uses the dotnet 6 as the installed sdk to resolve build issues detected on the release pipeline as outlined in #373 
We also install dotnet core version 2.x as the ESRP tasks need it for code signing.
> Use dotnet 6 in ci-build.yml

- tests/Microsoft.Graph.DotnetCore.Test/Microsoft.Graph.DotnetCore.Test.csproj
The [v1 test project](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/tests/Microsoft.Graph.DotnetCore.Test/Microsoft.Graph.DotnetCore.Test.csproj) targets 3.1
The current target [makes the generation fail](https://microsoftgraph.visualstudio.com/Graph%20Developer%20Experiences/_build/results?buildId=60847&view=logs&j=75842713-d241-5c51-b0b4-a337631cec97&t=c3da5ce4-958d-57ba-561a-54d688869703) after the upgrade of the pipeline to net 6.0
This PR aims to solve that.
> - updates target for test project to unblock beta generation

- tests/Microsoft.Graph.DotnetCore.Test/Mocks/MockHttpProvider.cs
- tests/Microsoft.Graph.DotnetCore.Test/Mocks/MockRedirctHandler.cs
- tests/Microsoft.Graph.DotnetCore.Test/Mocks/TestHttpMessageHandler.cs
This PR is related to https://github.com/microsoftgraph/msgraph-sdk-dotnet/pull/1194
It unblocks generation by applying similar changes reported in the PR above.
**Failing build** 
https://dev.azure.com/microsoftgraph/Graph%20Developer%20Experiences/_build/results?buildId=61672&view=logs&j=4c81e8e4-6eb9-5def-7261-b44ad0fc1b7d&t=d7256970-5877-5148-923c-bfd9787d6286
> Task disambiguation #2

- src/Microsoft.Graph/Microsoft.Graph.Beta.csproj
This is part of https://github.com/microsoft/kiota-abstractions-dotnet/issues/12
It changes the target runtime to netstandard2.0
> Change target runtime to netstandard 2.0

- CHANGELOG.md
- src/Microsoft.Graph/GraphServiceClient.cs
- src/Microsoft.Graph/Microsoft.Graph.Beta.csproj
This PR 
- Closes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1601 to create easier passing of IAuthenticationProvider when using the httpClient
- Update changelog and project for release 5.16.0
> Upgade guide update and release (beta)

- CHANGELOG.md
- src/Microsoft.Graph/Microsoft.Graph.Beta.csproj
beta sidekick of https://github.com/microsoftgraph/msgraph-sdk-dotnet/pull/1639
> Upgrade guide updates and release(beta)

- README.md
- src/Microsoft.Graph/Extensions/CustomBatchRequestBuilder.cs
- src/Microsoft.Graph/GraphServiceClient.cs
This PR depends on https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/637
Adds a derived BatchRequestBuilder to allow passing for errormappings to allow for consistent errors. and closes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1782
Also closes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1784
> Adds derived BatchRequestBuilder

- .github/policies/msgraph-beta-sdk-dotnet-branch-protection.yml
Initial commit [generated from the existing UI set branch policies using GH CLI](https://github.com/MIchaelMainer/policyservicetoolkit/blob/main/branch_protection_export.ps1). 
Carefully review the policy for additions and changes that should be added here. Review subsequent commits for changes to policy.
> IMPORTANT: Policy changes can be disruptive to workflows.
> - add branch protection policy file

- CHANGELOG.md
- src/Microsoft.Graph/Extensions/DateTimeTimeZoneExtensions.cs
- tests/Microsoft.Graph.DotnetCore.Test/Models/Extensions/DateTimeZoneExtensionsTests.cs
> Fixes DateTimeTimeZone.ToDateTime returning incorrect parsed date

- .gitignore
Fixes failure at https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/pull/850
CI pipeline fails to checkin the `BackupRestore` request builder due to the gitignore file causing passed build in pipeline but failure in PR.
> Update .gitignore to fix failed checkin of generated folder 

- CONTRIBUTING.md
Dummy commit to validate CI and release please working after branch renaming work
> docs: fixes typo in contribution guide

- src/Microsoft.Graph/GraphServiceClient.cs
- tests/Microsoft.Graph.DotnetCore.Test/Models/ModelSerializationTests.cs
- tests/Microsoft.Graph.DotnetCore.Test/Requests/Functional/OneNoteTests.cs
Follow up to https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/879
Cleans up obsolete methods in tests.
> fix: update to use non obsolete constructors and methods

- pipelines/ci-build.yml
- scripts/ValidateUpdatedNugetVersion.ps1
Follow up to changes at https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/pull/860
Fixes the validation script to look for the version in the `Version` tag rather than the `VersionPrefix` tag
Also makes the validation to be happen earlier as if we are going to fail, lets fail early..
> build: fix validate version update script to align to csproj changes

- pipelines/ci-build.yml
Fixes double tagging and double releases from CI and release please
> ci: fixing double tagging and GH releases

- src/Microsoft.Graph/Extensions/UploadSession.cs
- tests/Microsoft.Graph.DotnetCore.Test/Models/Extensions/UploadSessionTests.cs
Related to https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/903 to resolve trimming warnings due to reflection used.
Depends on merge of https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/pull/892
> fix: updated the UploadSession model to implement IUploadSession 

- src/Microsoft.Graph/Microsoft.Graph.Beta.csproj
Follows guidance at https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/8.0/trimming-unsupported-targetframework#recommended-action
Aligns with v1 repo at https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dcdd64e45c419fcf7a5c7c827da3cb14b3746557/src/Microsoft.Graph/Microsoft.Graph.csproj#L40C42-L40C69
> fix: Fixed incorrect trimming expression
